# -*- coding: utf-8 -*-
"""CS5542_ICP-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iQrV90vZvX19dtd2dDCzqFStYTmRa3R2
"""

from google.colab import drive
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Code to read csv file into Colaboratory:
pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

link = 'https://drive.google.com/file/d/1ShRHWtgHUV4m_8oC0ad-gSdXK7NKd8jM/view?usp=sharing' # The shareable link

downloaded = drive.CreateFile({'id':'1ShRHWtgHUV4m_8oC0ad-gSdXK7NKd8jM'}) 
downloaded.GetContentFile('ICP-1.csv')  
df = pd.read_csv('ICP-1.csv')


#check duplicates

duplicates = df.duplicated().sum()
print(df.columns)
print("Total duplicates : {}\n".format(duplicates))

#Drop dulicate if any 
df.drop_duplicates(inplace=True) 

#Count missing data
print("Null count: {}\n".format(df.isnull().sum()))

#print row index 1
#print(df.loc[[1]])


#Display all informations

print(df.head())

print(df.info())

print(df.describe())

#find out unique elements in a column of the dataset.
print("Check Unique by diagnosis: {} \n".format(df["diagnosis"].unique()))

#Boxplot
sns.boxplot(df['radius_mean'])

#regplot
sns.regplot(x='radius_mean',y='radius_se',data=df)